/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DisciplinesRouteImport } from './routes/disciplines'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as HallOfMasteryRouteImport } from './routes/hall-of-mastery'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesRoute = DisciplinesRouteImport.update({
  id: '/disciplines',
  path: '/disciplines',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfMasteryRoute = HallOfMasteryRouteImport.update({
  id: '/hall-of-mastery',
  path: '/hall-of-mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRoute
  '/fitness': typeof FitnessRoute
  '/focus': typeof FocusRoute
  '/hall-of-mastery': typeof HallOfMasteryRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRoute
  '/fitness': typeof FitnessRoute
  '/focus': typeof FocusRoute
  '/hall-of-mastery': typeof HallOfMasteryRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRoute
  '/fitness': typeof FitnessRoute
  '/focus': typeof FocusRoute
  '/hall-of-mastery': typeof HallOfMasteryRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/calendar'
    | '/disciplines'
    | '/fitness'
    | '/focus'
    | '/hall-of-mastery'
    | '/insights'
    | '/journal'
    | '/missions'
    | '/projects'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/calendar'
    | '/disciplines'
    | '/fitness'
    | '/focus'
    | '/hall-of-mastery'
    | '/insights'
    | '/journal'
    | '/missions'
    | '/projects'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/calendar'
    | '/disciplines'
    | '/fitness'
    | '/focus'
    | '/hall-of-mastery'
    | '/insights'
    | '/journal'
    | '/missions'
    | '/projects'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  CalendarRoute: typeof CalendarRoute
  DisciplinesRoute: typeof DisciplinesRoute
  FitnessRoute: typeof FitnessRoute
  FocusRoute: typeof FocusRoute
  HallOfMasteryRoute: typeof HallOfMasteryRoute
  InsightsRoute: typeof InsightsRoute
  JournalRoute: typeof JournalRoute
  MissionsRoute: typeof MissionsRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines': {
      id: '/disciplines'
      path: '/disciplines'
      fullPath: '/disciplines'
      preLoaderRoute: typeof DisciplinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-mastery': {
      id: '/hall-of-mastery'
      path: '/hall-of-mastery'
      fullPath: '/hall-of-mastery'
      preLoaderRoute: typeof HallOfMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  CalendarRoute: CalendarRoute,
  DisciplinesRoute: DisciplinesRoute,
  FitnessRoute: FitnessRoute,
  FocusRoute: FocusRoute,
  HallOfMasteryRoute: HallOfMasteryRoute,
  InsightsRoute: InsightsRoute,
  JournalRoute: JournalRoute,
  MissionsRoute: MissionsRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
